version: '3.7'

networks:
  my_network:
    name: 'my_network'

services:
  postgis:
    container_name: 'postgis_container'
    image: pgrouting/pgrouting:12-3.0-3.0.1
    networks:
      - my_network
    volumes:      
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
      - ./db/:/db/
    env_file:
      - ./.env
    ports:
      - "25432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 15s
      timeout: 5s
      retries: 3

  load_data:
    image: python:3.9-slim
    container_name: load_data
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "sleep 10 && pip install -r requirements.txt && python load_geojson.py"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 15s
      timeout: 5s
      retries: 3

  api:
    image: python:3.9-slim
    container_name: api
    depends_on:
      postgis:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - FLASK_APP=prueba.py
    ports:
      - "5001:5001"
    command: >
      sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0 --port=5001"

volumes:
  pgdata:
    driver: local
